name: Generate Snake

on:
  schedule: # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: shwan26 # Replace with your GitHub username
          color_snake: "#1E90FF" # Blue color for the snake

      - name: Upload the snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-snake.svg

      - name: Commit and push the snake
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Generate Snake Animation"
          git push
